<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="9.0.3" />
    <PackageReference Include="System.Security.Cryptography.Pkcs" Version="10.0.10" />
    <PackageReference Include="System.Security.Cryptography.Xml" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ElectronicBilling.Core\ElectronicBilling.Core.csproj" />
    <ProjectReference Include="..\ElectronicBilling.Application\ElectronicBilling.Application.csproj" />
    <ProjectReference Include="..\ElectronicBilling.Infrastructure\ElectronicBilling.Infrastructure.csproj" />
  </ItemGroup>

</Project>
